language: python

virtualenv:
  system_site_packages: true
  
env:
  matrix:
    #- DISTRIB="ubuntu" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"

    # This environment tests Python 2 support
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MKL="false"
      NUMPY_VERSION="1.9.2" SCIPY_VERSION="0.16.0"
      SKLEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.3"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"

    # This environment tests Python 3 support
    - DISTRIB="conda" PYTHON_VERSION="3.4" INSTALL_MKL="false"
      NUMPY_VERSION="1.9.2" SCIPY_VERSION="0.16.0"
      SKLEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.3"
      COVERAGE="true"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      
install: source distributions/ci/install.sh

script: source distributions/ci/run_tests.sh

after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls; fi

cache: apt
