language: python

virtualenv:
  system_site_packages: true

python:
  - "2.7"
  - "3.2"
  
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-sklearn

install:
  - pip install coverage
#  - pip install numpy scipy scikit-learn coverage

script:
  - nosetests --with-coverage --cover-package=scot,eegtopo --cover-erase --cover-inclusive --cover-branches
