language:
  python

sudo:
  false

virtualenv:
  system_site_packages:
    false
  
env:
  matrix:
    # oldest supported package versions on Python 2
    - DISTRIB="conda" PYTHON="2.7"
      NUMPY="1.8.2" SCIPY="0.13.3"
      SKLEARN="0.15.0" MATPLOTLIB="1.4.0"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="false"

    # oldest supported package versions on Python 3
    - DISTRIB="conda" PYTHON="3.5"
      NUMPY="1.8.2" SCIPY="0.13.3"
      SKLEARN="0.15.0" MATPLOTLIB="1.4.0"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="false"

    # Python 2
    - DISTRIB="conda" PYTHON="2.7"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="false"

    # Python 3
    - DISTRIB="conda" PYTHON="3.5"
      INSTALL_SCOT="true" RUN_EXAMPLES="false"
      COVERAGE="true"
      
install:
  source distributions/ci/install.sh

script:
  source distributions/ci/run_tests.sh

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then codecov; fi
